[package]
name = "front"
version = "0.1.0"
edition = "2021"

[lib]
path = "rs/lib.rs"

# we use 'rs' instead of 'src' since the bazel sandbox gives us a handle to our
# repository root, which is also named 'src'
[[bin]]
name = "front_main"
path = "rs/main.rs"


[dependencies]
wasm-bindgen = "=0.2.83"  # there's bug if we go to 0.2.84 that isn't resolved
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17.0"
web-sys = "0.3.60"  # latest web-sys compatible with wasm-bindgen 0.2.83
log = "0.4.17"
wasm-logger = "0.2.0"

yew_icons = {version = "0.7", features = [
    "BootstrapSoundwave", "BootstrapExclamationTriangle", "BootstrapTools",
    "BootstrapMap",
]}

stylist = { version = "0.12.0", features = ["yew"] }
time = "0.3.19"
