# Github actions has a 10x multiplier on minute usage for macos, and the
# minutes are more expensive, and the macos runners are 6-8x slower. So using
# them frequently really sucks.
#
# For now we don't worry about testing the ios app in CI. This workflow works
# and the caching is tested, but it damn slow.

name: Macos Test

#on: [pull_request]
on: []  # skip this workfow. 

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v3
        with:
          path: /private/var/tmp/_bazel_runner
          # On hit the cache is not updated, so we want cache keys to be very
          # specific and not hit exactly every time. The action will then look
          # at partial matches with restore-keys, which will reinstate a
          # partially-matching cache and let us also store a new one. We name
          # caches hierachically according to what changes most frequently
          # (rust/swift sources -> bazel build rules -> dependencies -> OS).
          # This way we preferentially reinstate caches that are more likely to
          # have a large number of build artifacts in common.
          key: bazel-cache-${{ runner.os }}-deps-${{ hashFiles('**/*.lock') }}-buildrules-${{ hashFiles('WORKSPACE', '**/BUILD', '.bazelversion') }}-src-${{ hashFiles('**/*.rs', '**/*.swift') }}
          restore-keys: |
            bazel-cache-${{ runner.os }}-deps-${{ hashFiles('**/*.lock') }}-buildrules-${{ hashFiles('WORKSPACE', '**/BUILD', '.bazelversion') }}
            bazel-cache-${{ runner.os }}-deps-${{ hashFiles('**/*.lock') }}
            bazel-cache-${{ runner.os }}

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-darwin-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-darwin-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Run tests
        run: |
          bazel run src/app/stem:db_gen
          bazel test //src/app/stem/...

      - name: Check format
        run: bazel build --@rules_rust//:rustfmt.toml=//:rustfmt.toml --aspects=@rules_rust//rust:defs.bzl%rustfmt_aspect --output_groups=rustfmt_checks //...

      - name: Clippy
        run: bazel build --aspects=@rules_rust//rust:defs.bzl%rust_clippy_aspect --output_groups=clippy_checks //...

