//! Generates a Sqlite database for sqlx to check queries against. Also creates
//! a `.env` file in `stem/` which tells sqlx where to find the database at
//! compile time.
//!
//! The database is placed in stem/dev/db, which is ignored by source control. The
//! directory is cleaned out every time this script runs.
//!
//! We need to run this script explicitly before we can build the app, due to
//! Bazel and developer energy constraints. Some notes on the challenges faced
//! in integrating this into the build flow:
//!
//! - If a program generates the database, Bazel will put it in bazel-out or
//! bazel-bin, where it is not in the same working directory as the compiler.
//! - We need to let sqlx know where the database is with the DATABASE_URL env
//! var. Depending on our build config, the output file will be in a different
//! output directory.

use std::fs;
use std::fs::File;
use std::io::Write;
use std::path::Path;

use std::{thread, time};

use sqlx::{
    migrate::MigrateDatabase, Connection, Sqlite, SqliteConnection, SqlitePool,
};

const DB_PREFIX: &str = "sqlite://";
const DB_FNAME: &str = "data.db";

async fn migrate_db(db_path: &str) -> Result<(), sqlx::Error> {
    if !Sqlite::database_exists(&db_path).await? {
        Sqlite::create_database(&db_path).await?;
    }
    let mut conn = SqliteConnection::connect(&db_path).await?;
    // embed our migrations from "migrations/" into our binary
    sqlx::migrate!().run(&mut conn).await?;
    conn.close().await.unwrap();
    Ok(())
}

#[tokio::main]
async fn main() {
    // Bazel sets this env var when we do `bazel run`. This is how we can add
    // files to the src directory
    let workspace_root_key = "BUILD_WORKSPACE_DIRECTORY";
    let workspace_root = std::env::var(workspace_root_key).expect(
        "Could not get BUILD_WORKSPACE_DIRECTORY environment variable. \
         This script should be run with Bazel: `bazel run :db_gen`",
    );
    println!("Found workspace root: {}", workspace_root);

    // Navigate to the stem directory where we will put the .env file
    let stem_dir = Path::new(&workspace_root).join("src/app/stem");
    std::env::set_current_dir(stem_dir.clone()).unwrap();
    println!("Set current working directory to: {}", stem_dir.display());

    // Set up the directory the database will live in (dev/db)
    let db_dir = stem_dir.join("dev/db");
    if fs::metadata(db_dir.clone()).is_ok() {
        // Clear it out if it had prior contents
        fs::remove_dir_all(db_dir.clone()).unwrap();
    }
    fs::create_dir(db_dir.clone()).unwrap();

    // Construct the database url.
    let db_url = format!("{DB_PREFIX}{}", db_dir.join(DB_FNAME).display());
    let dotenv_contents = format!("DATABASE_URL={}\n", db_url);

    // Write the database URL to the .env file
    let mut file = File::create(".env").unwrap();
    file.write_all(dotenv_contents.as_bytes()).unwrap();

    // Migrate the database
    migrate_db(&db_url).await.unwrap();

    // Need to touch data.db-shm and data.db-wal because sqlx can't create them
    // from within the sandbox.
    File::create(db_dir.join("data.db-wal")).unwrap();
    File::create(db_dir.join("data.db-shm")).unwrap();

    // Let's also leave a note to not store files in the directory
    File::create(db_dir.join("DIR_CONTENTS_AUTOGENERATED_BY_db_gen")).unwrap();
}
