name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-cache

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-darwin-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-darwin-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Run tests
        run: |
          bazel run src/app/stem:db_gen
          bazel test //src/app/stem/...

