name: scoria-site
region: sfo
services:
  - name: scoria-site
    image:
      deploy_on_push:
        enabled: true
      registry_type: DOCR
      repository: site
      tag: latest
    http_port: 8000
    health_check:
      http_path: /health_check
    routes:
      - path: /
    instance_count: 1
    instance_size_slug: professional-xs
    envs:
      - key: APP_DATABASE__USERNAME
        scope: RUN_TIME
        value: ${feedback.USERNAME}
      - key: APP_DATABASE__PASSWORD
        scope: RUN_TIME
        value: ${feedback.PASSWORD}
      - key: APP_DATABASE__HOST
        scope: RUN_TIME
        value: ${feedback.HOSTNAME}
      - key: APP_DATABASE__PORT
        scope: RUN_TIME
        value: ${feedback.PORT}
      - key: APP_DATABASE__DATABASE_NAME
        scope: RUN_TIME
        value: ${feedback.DATABASE}
      # We use DO's APP_URL to inject the dynamically
      # provisioned base url as an environment variable
      - key: APP_APPLICATION__BASE_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: APP_ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: APP_TURNSTILE__SITE_KEY
        scope: RUN_TIME
        value: REPLACE_WITH_TURNSTILE_SITE_KEY
      - key: APP_TURNSTILE__SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: REPLACE_IN_DASHBOARD
domains:
- domain: scoria.info
  type: PRIMARY
  zone: scoria.info
- domain: www.scoria.info
  type: ALIAS
  zone: scoria.info
databases:
  - engine: PG
    name: feedback
    num_nodes: 1
    size: db-s-dev-database
    version: "12"
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
